services:
  postgres-event-processor:
    extends:
      file: events-processor-services.yml
      service: postgres-event-processor
  redis:
    extends:
      file: events-processor-services.yml
      service: redis
  events-processor:
    extends:
      file: events-processor-services.yml
      service: events-processor

  graph-node:
    extends:
      file: graph-node-services.yml
      service: graph-node
  graph-node-postgres:
    extends:
      file: graph-node-services.yml
      service: graph-node-postgres
  ipfs:
    extends:
      file: graph-node-services.yml
      service: ipfs
  subgraph-deployer:
    extends:
      file: graph-node-services.yml
      service: subgraph-deployer

  testnet:
    build:
      dockerfile: ./services/testnet/Dockerfile
      context: .
    ports:
      - "8545:8545"

  fake-pinata:
    build:
      dockerfile: ./services/fake-pinata/Dockerfile
      context: .
    ports:
      - '3000:3000'

  app:
    build:
      dockerfile: ./services/app/Dockerfile
      context: .
