services:
  postgres-event-processor:
    image: postgres
    ports:
      - '5433:5432'
    command: ["postgres", "-cshared_preload_libraries=pg_stat_statements"]
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: dripsdb
      POSTGRES_INITDB_ARGS: -E UTF8 --locale=C

  redis:
    image: redis:latest
    restart: unless-stopped
    ports:
      - '6379:6379'
