services:
  graph-node-postgres:
    image: postgres
    command: ["postgres", "-cshared_preload_libraries=pg_stat_statements"]
    environment:
      POSTGRES_USER: graph-node
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: graph-node
      POSTGRES_INITDB_ARGS: -E UTF8 --locale=C

  ipfs:
    image: ipfs/go-ipfs

  graph-node:
    image: graphprotocol/graph-node
    depends_on:
      - ipfs
      - graph-node-postgres
      - testnet
    environment:
      postgres_host: graph-node-postgres
      postgres_user: graph-node
      postgres_pass: postgres
      postgres_db: graph-node
      ipfs: 'ipfs:5001'
      ethereum: "goerli:http://testnet:8545"
      GRAPH_LOG: info

  subgraph-deployer:
    build:
      dockerfile: ./services/subgraph-deployer/Dockerfile
      context: .
    depends_on:
      - testnet
      - graph-node
